### ISSUE TITLE
not support ! to exclude in workspace config

### ISSUE THREAD

**Issue by wuwb** [QuiiBz/sherif#62] opened 2024-04-30 05:16 UTC
not support ! to exclude in workspace config

```
packages:
  - 'clients/*'
  - '!clients/mobile'
```

shows no package.json in client//package.json

**Comment by QuiiBz** [comment] 2024-06-18 10:19
Closing as no reproduction has been provided and we can't reproduce the issue.

**Closed by QuiiBz** 2024-06-18 10:19 UTC
Labels: bug
